# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20161101_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.IntegerField()),
                ('bad', models.IntegerField()),
                ('meh', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='game',
            name='descriptions',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polls',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Game'),
        ),
    ]
