# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20161101_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='bad',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='good',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='meh',
        ),
        migrations.AddField(
            model_name='poll',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
