# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_game_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pic',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
