# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_auto_20161103_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyWeather',
        ),
    ]
