# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20161102_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='poll',
            name='choice_text',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
